---
- name: Make Self-Signed certificate to sginx
  shell: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/nginx-selfsigned.key -out /etc/pki/tls/certs/nginx-selfsigned.crt -subj "/C=BR/ST=Sao Paulo/L=Sao Paulo/O=project/OU=TI/CN=myproject.com"'

- name: Remove nginx.conf default
  file:
   name: /etc/nginx/nginx.conf
   state: absent

- name: Copy a personalize nginx.conf file
  template:
   src: nginx.j2
   dest: /etc/nginx/nginx.conf

- name: Enable and start nginx service
  systemd:
   name: nginx
   enabled: yes
   state: started
