---
- name: Start DB
  systemd:
   name: mariadb
   enabled: yes
   state: started

- name: Remove all anonymous users
  mysql_user:
   name: ''
   host_all: yes
   state: absent

- name: Set root password for DB
  mysql_user:
   name: root
   password: "{{ mariadb_root_password }}"
   host: localhost
   state: present

- name: Create database's project
  mysql_db:
   name: project
   state: present

- name: Create a user for project and grant permission
  mysql_user:
   name: user_project
   password: "{{ bd_user_pass }}"
   priv: 'project.*:ALL'
   state: present
