---
- name: Create app user
  user:
   name: app_user
   comment: User to run app
   shell: /sbin/nologin
  tags: deploy_app

- name: Clone github Repo
  git:
   repo: https://github.com/reversondias/Myproject.git
   dest: /Myproject
   clone: yes
  tags: deploy_app

- name: Install requirements python app
  pip:
   requirements: /Myproject/requirements.txt
  tags: deploy_app

- name: Reconfigure de db.conf of App
  template:
   src: db.conf.j2
   dest: /Myproject/conf/db.conf
  tags: deploy_app

- name: Copy ervice unit file of Project App
  template:
   src: gunicorn.j2
   dest: /etc/systemd/system/gunicorn.service
   owner: root
   group: root
   mode: 0644
  tags: deploy_app

- name: Enable and Start Gunicorn service
  systemd:
   name: gunicorn
   enabled: yes
   state: started
  tags: deploy_app
