---
- name: Install epel repository
  yum:
   name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
   state: present
  tags: database, deploy_app

- name: Install requirements packages
  yum: 
   name: "{{ packages }}"
   state: latest
  tags: packages, deploy_app
 
 
